### ISSUE TITLE
[docs] getting image data doc clarification

### ISSUE THREAD

**Issue by chrisgervang** [visgl/loaders.gl#632] opened 2020-01-28 19:39 UTC
I'm using version 2.0.2 to load PNGs with the goal of accessing an arraybuffer of RGBA data. While looking up the docs I found it should be possible to do following instructions on these pages, but they are inconsistent. Below I've highlighted a few different documentation methods that didn't work in my testing. At the bottom I've added code that works.

https://loaders.gl/modules/images/docs/api-reference/image-loader | https://loaders.gl/docs/specifications/category-image
------------ | -------------
![IMG_4002](https://user-images.githubusercontent.com/2461547/73298058-88553300-41c1-11ea-8c20-9fc0e5a3957f.jpg) | ![IMG_4001](https://user-images.githubusercontent.com/2461547/73298060-88edc980-41c1-11ea-8bd6-0d24d7f00960.jpg) This method results in a type not supported error.
intentionally blank | ![IMG_3998](https://user-images.githubusercontent.com/2461547/73298063-88edc980-41c1-11ea-8987-f4ffbaae1ea5.jpg)
intentionally blank | ![IMG_3999](https://user-images.githubusercontent.com/2461547/73298062-88edc980-41c1-11ea-8c75-3f357110eed5.jpg) getImageData works, but the other mentioned method does not.

In the end I got it to work with this:
```
import { registerLoaders, load } from "@loaders.gl/core";
import { ImageLoader, getImageData, getImageSize } from "@loaders.gl/images";
registerLoaders(ImageLoader)
await load(imageLink).then(img => ({data: getImageData(img), size: getImageSize(img)}))
```

**Comment by ibgreen** [comment] 2020-01-28 19:56
@chrisgervang Great to see that the ImageLoader is being used to its full extent! I suspect you are using this for your terrain PRs and that is one of the primary use cases it was designed for.

The issue is that the `data` option is a work in progress for `loaders.gl 2.1` and not all PRs have landed, but the docs have still been updated (as part of a big push to lift the quality of the image 
module docs).

I apologize for that, I'll take a look at it this week and get it sorted. 

Perhaps we can start marking each API option with the loaders.gl version it was added in, to reduce confusion, it would have been especially useful in this case - as we have published docs that in a sense are referencing features from a "future release", at least that would have been clear.

**Comment by chrisgervang** [comment] 2020-02-05 02:19
Oh that's great news. Yes, the terrain layer was were I've been utilizing image loaders.. it was very helpful!

Once loaders is updated, I can bring the new API into the TerrainLayer. For now, I've got an experimental version ready to land here: https://github.com/uber/deck.gl/pull/3984

**Closed** 2021-02-07 19:37 UTC
