### ISSUE TITLE
Tile-converter generates wrong bounding volume

### ISSUE THREAD

**Issue by landajaromir** [visgl/loaders.gl#2586] opened 2023-08-15 08:22 UTC
Hi, 
I am trying to convert I3S to 3D Tiles. The I3S is created in ArcGIS Pro by exporting to SLPK and uploaded to arcgis servers. 
The final 3D are then loaded to CesiumION. 

However, all converted 3D tiles have wrong boundingVolume displayed in Cesium (
<img width="819" alt="Snímek obrazovky 2023-08-15 v 10 21 12" src="https://github.com/visgl/loaders.gl/assets/20437266/b482d935-3003-4dbe-bda5-74054ea73441">

Anyone know what could be the problem? The service for testing is here: https://tiles.arcgis.com/tiles/lOWgvXGCzs0MJj0p/arcgis/rest/services/water_new_geoiod2008_all/SceneServer/layers/0

Thank you

**Comment by belom88** [comment] 2023-08-15 09:28
Hi, @landajaromir!

I cannot reproduce it.

![image](https://github.com/visgl/loaders.gl/assets/18549629/d01823bd-37bf-4193-9431-343fa04552ea)


Could you give more details:
* How do you run conversion (comman line)?
* Operating System;
* NodeJS version.

**Comment by landajaromir** [comment] 2023-08-15 09:48
> https://tiles.arcgis.com/tiles/lOWgvXGCzs0MJj0p/arcgis/rest/services/water_new_geoiod2008_all/SceneServer/layers/0

Wow, that is strange. The conversion is from command line: 
npx tile-converter --input-type I3S --tileset https://tiles.arcgis.com/tiles/lOWgvXGCzs0MJj0p/arcgis/rest/services/water_new_geoiod2008_all/SceneServer/layers/0 --name WATER

I am on MacOS Ventura, NodeJS version 16.20.1 and npx 8.19.4.

**Comment by belom88** [comment] 2023-08-15 11:43
It seems there is a bug on 3.4. You can try some beta version by tag:
```
npm install @loaders.gl/tile-converter@beta
```

Or you can try a specific version:
```
npm install @loaders.gl/tile-converter@4.0.0-alpha.18
```

**Comment by landajaromir** [comment] 2023-08-15 12:34
The new version cannot be installed. It shows the conflict with code and i3s module expecting different versions. 

If I delete node modules and install new version, than the tile-converter command does not work and I cannot install dependencies.

**Comment by belom88** [comment] 2023-08-15 13:14
So, I can reproduce your issue on @loaders.gl/tile-converter@4.0.0-alpha.17 as well. 4.0.0-alpha.18 is broken although I could convert you dataset in test environment.
I will take a look what is wrong there.

**Comment by landajaromir** [comment] 2023-08-15 13:15
Thank you so much.

**Comment by belom88** [comment] 2023-08-15 16:10
The fix is in 4.0.0-alpha.19
```bash
  mkdir tmp
  cd tmp
  npm install @loaders.gl/tile-converter@4.0.0-alpha.19
  npx tile-converter --install-dependencies
  npx tile-converter --input-type I3S --tileset https://tiles.arcgis.com/tiles/lOWgvXGCzs0MJj0p/arcgis/rest/services/water_new_geoiod2008_all/SceneServer/layers/0 --name WATER
```

**Comment by landajaromir** [comment] 2023-08-16 17:24
It works, thank you so much.

**Comment by dsactionengine** [comment] 2023-08-17 10:23
Can confirm it works now on alpha 19.
Total conversion time: 2s
Vertex count:  69
File(s) size:  5157  bytes
<img width="861" alt="image" src="https://github.com/visgl/loaders.gl/assets/128065385/1d4a53c6-131d-41c4-b837-cfd6f36ea7ba">

**Closed** 2023-08-17 10:24 UTC
Labels: bug, ActionEngine
