### ISSUE TITLE
add my custom 3dtiles data : Wrong angle

### ISSUE THREAD

**Issue by tommy2gis** [visgl/loaders.gl#982] opened 2020-10-19 09:41 UTC
tileset file : http://geowork.wicp.vip:25081/gateway/3dtiles/rugaocq/tileset.json

**in mapboxgl use  Tiles3DLoader**

![微信截图_20201019173334](https://user-images.githubusercontent.com/1844959/96427583-52fde300-1231-11eb-818b-eb1a6874589c.png)

**in cesium use Cesium3DTileset is right**

![image](https://user-images.githubusercontent.com/1844959/96427871-a8d28b00-1231-11eb-96fa-0e42674758fb.png)

**Comment by ibgreen** [comment] 2020-10-19 18:38
Duplicate of #921? 

Are you using same converter that is generating a non-standard `gltfAxis` field?

If so we have a fix but it just missed loaders.gl 2.3-release and would need to be back ported.

**Closed** 2020-10-20 01:40 UTC
