### ISSUE TITLE
cesium point clouds disappearing

### ISSUE THREAD

**Issue by Radik24** [visgl/loaders.gl#1384] opened 2021-05-17 06:20 UTC
Hi,

I'm facing an issue with Cesium point cloud in deck.gl (Tile3DLayer + Tiles3DLoader). Sometimes most of the points disappear and after a small move with the mouse I can see detailed point cloud again. So I think the data is correct??. Is there any parameter in deck.gl or loaders.gl to fix this issue? I thought it can be refinement in 3d tiles. I set it in the root tile ('REPLACE', 'ADD') but without any change. 

I opened a discussion in deck.gl repo https://github.com/visgl/deck.gl/discussions/5776, but I was asked to move it here.

```
new Tile3DLayer({
        id: layer.label,
        data: `${api_url}/tileset.json`,
        loader: Tiles3DLoader,
        pointSize: layer.pointSize || 1
})
```

At the beginning of the video you can see only few points (and it's flickering sometimes).

https://user-images.githubusercontent.com/23722745/118234282-6c979e00-b493-11eb-9022-b90900a00317.mov

Any ideas what is wrong, or where can I look for a bug?

Thanks!

**Comment by dryabinin-actionengine** [comment] 2021-05-20 09:29
@Radik24 Hello. Thanks for the questions. We will take a look on that and let you know about results. Is it possible for you to provide a tileset which you shown for debugging purposes?

**Comment by ibgreen** [comment] 2021-06-01 18:15
@belom88 @dryabinin-actionengine - I am starting to suspect that the reason we don't see this in I3S is that we are using additive refinement, which we shouldn't be doing for mesh tiles (it is mostly useful for point clouds).

@Avnerus did you run into this in your work? is it addressed by your changes?

**Comment by Avnerus** [comment] 2021-06-01 19:36
@ibgreen It might be addressed! It sounds similar to problems I've been having with empty traversal (traversal of nested tileset jsons). If possible, please try my fork of loaders.gl and see if it resolves the issue.

**Comment by belom88** [comment] 2021-06-02 17:45
Well, we still need the tileset url and token to reproduce the issue.

**Comment by ibgreen** [comment] 2021-06-02 18:48
Suggest we try to land @Avnerus changes and publish, then the original reporter can test again on their files.

**Comment by Radik24** [comment] 2021-06-02 18:52
Hi, I sent some data to @dryabinin-actionengine

**Comment by dryabinin-actionengine** [comment] 2021-06-03 09:26
@Radik24 Yes we will check using your data which you are provided to me on the @Avnerus fork of loaders.gl.

**Comment by dryabinin-actionengine** [comment] 2022-03-15 08:45
Hello @Radik24! 
Unfortunately we still have such issue in open state, I know @Avnerus had some related work on it but I don't know about results.
Also I found that you assets are not available any more. Could you share one more to reproduce an issue?

**Comment by dryabinin-actionengine** [comment] 2022-05-06 13:15
Agreed to reach out for @Pessimistress to resolve the issue on 16 March. Will close the issue. @Radik24 If it is not resolved please reopen it again.

**Closed** 2022-05-06 13:16 UTC

**Comment by aybond** [comment] 2022-05-17 19:03
Greetings all.

I had a similar flicker problem as @Radik24 when I switched to a newer version of deck.gl.
I found that before the **@deck.gl/geo-layers** module was using the **@loaders.gl/tiles@3.1.0** version, everything was fine! 
I'm guessing that this commit or the one next to it is the clue: https://github.com/visgl/loaders.gl/commit/88ed87945792c39f258e980a73537851fd46a52d
Maybe @dryabinin-actionengine can help fix this problem after this post.

My current script works around the flicker problem for deck.gl version **8.7**: 
`cd ./node_modules/@deck.gl/geo-layers && yarn add @loaders.gl/tiles@3.1.0`
But for deck.gl version **8.8.0-alpha.2** this script is obsolete due to a backwards compatibility violation for the **@deck.gl/geo-layers** module in relation to the **@loaders.gl/tiles** module - here is the reference commit: https://github.com/visgl/deck.gl/commit/51aba01cfa5ecdf88afff79a8b211c987a933c5f

Regards!
