### ISSUE TITLE
Various ts compiler errors

### ISSUE THREAD

**Issue by nopor** [visgl/loaders.gl#1828] opened 2021-09-06 07:32 UTC
(related to https://github.com/visgl/loaders.gl/issues/1804)

loader.gl version(s): [3.0.9 - 3.1.0-alpha.2]

Due to the following errors (see attached error.log), the library can't be compiled anymore.
[error.log](https://github.com/visgl/loaders.gl/files/7114081/error.log)

There are 6 kinds of errors (189 errors in total):
- error TS7006: Parameter [various names] implicitly has an 'any' type
- error TS6133: [various names] is declared but its value is never read
- error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'. No index signature with a parameter of type 'string' was found on type '{}'
- error TS2304: Cannot find name 'importScripts'
- error TS7051: Parameter has a name but no type. Did you mean [various suggestions]?
- error TS7008: Member [various names] implicitly has an 'any' type.

**Comment by ibgreen** [comment] 2021-09-06 16:25
Thanks for reporting. In 3.0 we updated the entire code base to `.ts`. To make it manageable we didn't enable all typescript checks, such as noImplicityAny. 

While we work on this, I assume that setting `skipLibChecks` in your tsconfig.json makes it work? We do import loaders.gl successfully in many applications.

**Comment by davidcalhoun** [comment] 2021-09-14 18:22
Running into the same issue here even with `"skipLibCheck": true,` in `tsconfig.json` or when running it via the command line - `tsc --skipLibCheck`

**Comment by nopor** [comment] 2021-09-15 07:46
Thanks for your replies.
Unfortunately this also happens with `skipLibChecks`. I set up a small repo to demonstrate the issue, if you like to check it out: https://github.com/nopor/loaders.gl-compiler-issue

Of course, if we would ignore `any` and disable the strict mode, we would 'only' run into one other issue with the current version (3.0.12):
```
node_modules/@loaders.gl/loader-utils/src/json-loader.ts:21:51 - error TS2304: Cannot find name 'TextDecoder'.

21   parse: async (arrayBuffer) => parseTextSync(new TextDecoder().decode(arrayBuffer)),
[...]
node_modules/@loaders.gl/worker-utils/src/lib/worker-utils/get-transfer-list.ts:53:63 - error TS2304: Cannot find name 'ImageBitmap'.

53   if (typeof ImageBitmap !== 'undefined' && object instanceof ImageBitmap) {
                                                                                                            ~~~~~~~~~~~
Found 60 errors.
```

**Comment by ibgreen** [comment] 2021-09-15 16:05
@nopor Thanks for setting up a repo that reproduces this. We will take a look and loop back.

**Comment by Alek-S** [comment] 2021-09-15 20:03
Can confirm I still get the `any` error with `"skipLibCheck": true, `. My workaround was to add `"noImplicitAny": false` to my own ts config temporarily.

That doesn't however resolve the issue with `Type error: Cannot find name 'importScripts'.` which causes the build to fail. Don't have a workaround for that. Using it with Next.js `11.1.2`.

**Comment by peaceshi** [comment] 2021-09-17 09:02
> Can confirm I still get the `any` error with `"skipLibCheck": true, `. My workaround was to add `"noImplicitAny": false` to my own ts config temporarily.
> 
> That doesn't however resolve the issue with `Type error: Cannot find name 'importScripts'.` which still causes the build to fail. Don't have a workaround for that. Using it with Next.js `11.1.2`.
> 
> v2.x builds as expected, so downgraded to that for now.

https://nextjs.org/docs/api-reference/next.config.js/ignoring-typescript-errors

![image](https://user-images.githubusercontent.com/10380828/133755305-ad0a34d7-54b1-41cc-9170-22f742096ec4.png)

But I think loaders.gl should use [ts-ignore or ts-expect-error](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#ts-ignore-or-ts-expect-error) immediately.

**Comment by sanitul** [comment] 2021-11-29 12:49
Hi @ibgreen, Thanks for the TypeScript support but I still got the `implicitly has an 'any' type` and some others errors like `Cannot find name 'importScripts'`.
And I can not apply `"noImplicitAny": false` because of the project strict rules.
As I observe from `loader.gl version 3.1.0-beta.2` I got no TypeScript compile error. But the current stable version maybe `v3.0.13`, which has tsc errors. 
So what you suggest? Which version [3.x.x beta] should I used to fix this issue until next stable version release?

**Comment by ibgreen** [comment] 2021-11-29 15:26
@sanitul 

- Yes did a major overhaul of the typescript build system in 3.1 specifically to fix this issue. 
- It will not be fixed in 3.0. 
- We are trying to get an official 3.1 release out asap.
- Thanks for confirming that 3.1-beta solves the problem for you.

**Comment by davidcalhoun** [comment] 2022-01-13 00:25
Quick followup: everything looks good for us now using @loaders.gl@3.1.4`.  No more TS errors!  Thanks for your hard work.

I confirmed this in deck.gl's Slack but forgot to mention it here to close the loop!

**Comment by ibgreen** [comment] 2022-01-13 00:44
Thanks for confirming again. Then we can finally put this one to rest.

**Closed by ibgreen** 2022-01-13 00:44 UTC

**Comment by nopor** [comment] 2022-01-13 18:16
Can confirm that 3.1.4 is working great. Thank you for your effort.
