### ISSUE TITLE
crunch-loader loads textures and causes the page to freeze

### ISSUE THREAD

**Issue by hpugis** [visgl/loaders.gl#1848] opened 2021-09-23 08:04 UTC
This problem occurs when using crunch-loader：
![image](https://user-images.githubusercontent.com/49228502/134474162-72c163c1-55e7-40e9-9da8-3cc4d479329a.png)

There seems to be a problem in this section of the c++ code（https://github.com/richgel999/crunch-1/blob/master/inc/crn_decomp.h）：
![image](https://user-images.githubusercontent.com/49228502/134474119-f0710b3f-bfb5-402b-a9f7-58f28467b16a.png)
Is it a version issue of this version of crunch.js?

**Comment by hpugis** [comment] 2021-10-21 05:53
Yes, it seems that when crunch.js is decoded, the page is stuck due to a looping error, and the test data can run, occasionally causing this error @ibgreen

**Comment by ibgreen** [comment] 2021-11-29 15:18
@hpugis Not quite sure what is going on, since you are forking the code. I will close this issue but we can continue discussions here or in the discussions tab. 

In can't tell what your fork is doing, but probably the crunch JS code should not be transpiled again. Perhaps in your setup it is transpiled which breaks?

Perhaps we can make the some changes to the GLTFLoader so that you can just register the crunch loader globally, then you should should not need to import the crunch loader in parse-gltf. 

If you are having problems using the provided crunch worker and want help debugging you will need to provide a minimal reproducible example.

**Comment by belom88** [comment] 2021-12-09 09:27
I've fixed the issue with Crunch on the loaders.gl https://github.com/visgl/loaders.gl/pull/1997 . It will possibly fix this one as well.

**Closed** 2021-12-09 19:22 UTC
